Repository softeerbootcamp-3nd/softee5-hyundaittakdae-BE, pull requests merged in 2024-01, with the labels that each got.

#2 [Feat] 프로젝트 기본 세팅
  build.gradle
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/ApiResponse.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/code/BaseCode.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/code/BaseErrorCode.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/code/ErrorDTO.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/code/SuccessDTO.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/code/statusEnums/ErrorStatus.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/code/statusEnums/SuccessStatus.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/exception/ExceptionAdvice.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/exception/GeneralException.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/exception/handler/GeneralHandler.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/config/SwaggerConfig.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/controller/TestController.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/converter/TestConverter.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/dto/request/TestRequestDTO.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/dto/response/TestResponseDTO.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/User.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/service/TestService.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/service/TestServiceImpl.java
Labels: :seedling: feature, :tiger: yeji

#10 [Build] EC2 서버 배포 및 H2 연결
  src/main/resources/application.yml
Labels: :tiger: yeji, :wrench: build

#13 [Build] GitHub Actions를 활용한 CI/CD 구축2
  .github/workflows/dev_deploy.yml
Labels: :tiger: yeji, :wrench: build

#14 [Build] GitHub Actions를 활용한 CI/CD 구축3
  .github/workflows/dev_deploy.yml
Labels: :tiger: yeji, :wrench: build

#17 [Feat] Entity 설계 및 단방향 매핑
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/Amenities.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/Menu.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/Rating.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/RestArea.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/Restaurant.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/Review.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/Road.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/common/BaseEntity.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/enums/ReviewTag.java
Labels: :seedling: feature, :tiger: yeji

#23 [Feat] 식당 인기 메뉴 목록 조회 API 구현
  src/main/java/hyundai_6th_team/hyundai_6th_team/controller/RestAreaController.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/converter/MenuConverter.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/dto/response/RestaurantResponse.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/Menu.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/MenuRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/service/RestaurantService.java
Labels: :seedling: feature, :tiger: yeji

#25 [Feat] 휴게소 식당목록 및 메뉴목록 조회 API
  src/main/java/hyundai_6th_team/hyundai_6th_team/controller/RestAreaController.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/converter/MenuConverter.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/converter/RestAreaConverter.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/dto/response/RestAreaResponse.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/dto/response/RestaurantResponse.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/MenuRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/RestaurantRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/service/RestaurantService.java
Labels: :seedling: feature, :tiger: yeji

#28 [Feat] 휴게소 사진 업로드 API 구현
  build.gradle
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/code/statusEnums/ErrorStatus.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/config/AmazonS3Config.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/controller/DummyController.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/RestArea.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/RestAreaRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/service/AmazonS3Service.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/service/RestAreaService.java
Labels: :seedling: feature, :tiger: yeji

#34 [Feat] 휴게소 후기 + 메뉴 평점 API 구현
  src/main/java/hyundai_6th_team/hyundai_6th_team/controller/ReviewController.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/dto/response/ReviewDto.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/RestArea.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/Restaurant.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/enums/ReviewTag.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/MenuRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/RatingRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/RestAreaRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/ReviewRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/service/ReviewService.java
Labels: :seedling: feature, 🐉 LSH

#42 [Feat] 휴게소 후기 조회 API 구현
  src/main/java/hyundai_6th_team/hyundai_6th_team/apiPayload/code/statusEnums/ErrorStatus.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/controller/ReviewController.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/dto/response/ReviewResponse.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/ReviewRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/service/ReviewService.java
Labels: :seedling: feature, :tiger: yeji

#43 [Feat] 휴게소 특정 목록 조회 API 구현
  src/main/java/hyundai_6th_team/hyundai_6th_team/controller/RestAreaController.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/dto/response/RestAreaResponse.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/RestArea.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/entity/enums/ReviewTag.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/RestAreaRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/repository/ReviewRepository.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/service/RestAreaService.java
Labels: :seedling: feature, 🐉 LSH

#45 [Feat] 휴게소 식당목록 조회 API 구현
  src/main/java/hyundai_6th_team/hyundai_6th_team/controller/RestAreaController.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/converter/RestaurantConverter.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/dto/response/RestAreaResponse.java
  src/main/java/hyundai_6th_team/hyundai_6th_team/service/RestaurantService.java
Labels: :seedling: feature, :tiger: yeji
